"""add topic progress tracking

Revision ID: 2479847ac6c9
Revises: a38df10d82f1
Create Date: 2026-09-17 01:30:37.661329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2479847ac6c9'
down_revision = 'a38df10d82f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_practiced_at', sa.DateTime(), nullable=True),
    sa.Column('best_score', sa.Integer(), nullable=False),
    sa.Column('best_total', sa.Integer(), nullable=False),
    sa.Column('best_percentage', sa.Float(), nullable=False),
    sa.Column('last_attempt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_attempt_id'], ['attempt.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_topic_progress_user_topic')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_progress')
    # ### end Alembic commands ###
