"""add comprehension passages

Revision ID: a38df10d82f1
Revises: 6619581c10a1
Create Date: 2026-09-17 00:45:53.609701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38df10d82f1'
down_revision = '6619581c10a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('passage_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('audio_text', sa.Text(), nullable=True),
    sa.Column('audio_accent', sa.String(length=20), nullable=False),
    sa.Column('audio_rate', sa.Float(), nullable=False),
    sa.Column('max_audio_plays', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passage_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'passage', ['passage_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('passage_id')

    op.drop_table('passage')
    # ### end Alembic commands ###
