"""add adaptive diagnostic state

Revision ID: fb1c0be1ebd7
Revises: 2479847ac6c9
Create Date: 2026-09-17 02:37:05.227124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1c0be1ebd7'
down_revision = '2479847ac6c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_stage', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('diagnostic_direction', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('diagnostic_path', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('result_profile', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_attempt', schema=None) as batch_op:
        batch_op.drop_column('result_profile')
        batch_op.drop_column('diagnostic_path')
        batch_op.drop_column('diagnostic_direction')
        batch_op.drop_column('current_stage')

    # ### end Alembic commands ###
